version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - db
    ports:
      - 5432:5432


networks:
  db:
    driver: bridge
